FORMAT: 1A

# Password Metadata API

# Password [/password-check]
## Check password [POST]

+ Request
    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "password": "password"
            }

+ Response 200
    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "valid": false
            }


+ Request
    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "password": "+M\\)?3Wt9:[/g%m*sVF!"
            }

+ Response 200
    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "valid": true
            }
